SET(CMAKE_CXX_FLAGS "-msse4")
SET(CMAKE_CXX_FLAGS_DEBUG "-g -D_DEBUG")
SET(CMAKE_CXX_FLAGS_RELEASE "-O3")
SET(CMAKE_CXX_FLAGS_RELWITHDEBINFO "-g -O3")

SET(CMAKE_C_FLAGS "-msse4")
SET(CMAKE_C_FLAGS_DEBUG "-g -D_DEBUG")
SET(CMAKE_C_FLAGS_RELEASE "-O3")
SET(CMAKE_C_FLAGS_RELWITHDEBINFO "-g -O3")
